version: '3.2'

services:
  redis:
    image: redis

  postgres:
    image: postgres
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres:/var/lib/postgresql/dump

    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
  
  main:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ID_CUSTOMER: $ID_CUSTOMER
      ID_ACTOR: $ID_ACTOR
    depends_on:
      - redis
      - postgres